version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:058264063376:service/Swiggy_cluster/swiggy_svc"
        LoadBalancerInfo:
          ContainerName: "swiggy"
          ContainerPort: 3000