version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:iam::058264063376:role/service-role/codebuild-Swiggy_clone-service-role"
        LoadBalancerInfo:
          ContainerName: "swiggy"
          ContainerPort: 3000